server:
  port: 8080

spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/smartfarming?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: mudahemukafidela90@gmail.com
    password: "vioa vmww oadb amit"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

app:
  jwt:
    secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9c
    expirationInMs: 86400000 # 24 hours

logging:
  level:
    org.springframework.security: DEBUG
